name: deploy_backend

on:
    push:
        branches: [main]
        paths:
         - 'backend/**'   

env:
   AZURE_FUNCTIONAPP_NAME: counter1
   AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'
   DOTNET_VERSION: '6.0'

jobs:
    build-and-deploy:
        runs-on: windows-latest
        steps:
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
              creds:  ${{ secrets.AZURE_CREDENTIALS }}

        - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ env.DOTNET_VERSION }}   
        
        - name: 'Resolve Project Dependencies Using Dotnet'
          shell: pwsh
          run:  |
            pushd ' ./${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api'     
            dotnet build --configuration Release --output ./output
            popd
        - name: 'Run unit test'
          shell: pwsh
          run: |
            pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/tests'
            dotnet test
        - name: 'Run Azure Function Action'
          uses: Azure/functions-action@v1
          id: fa
          with:
            app-name: ${{ env.AZURE_FUNCTIONAPP_NAME}}
            package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api/output'    





